FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum /app/

RUN go mod download

COPY . .

RUN go build -o authentication ./cmd/api 

# RUN 

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/authentication .

EXPOSE 8080

CMD ["./authentication"]